### ISSUE TITLE
我想在你代码的基础上做开发，请问应该怎么本地引用？

### ISSUE THREAD

**Issue by wangsuidou** [helicopters/wc-messagebox#1]
我想在你代码的基础上做开发，请问应该怎么本地引用？

**Comment by helicopters** [comment]
... 之前没有看到, 你把当前的 仓库下载到本地, 提取出 src/wc-messagebox 即可.

**Comment by DogJun** [comment]
wc-utils/merge in ./src/base/wc-messagebox/components/Confirm/index.js, ./src/base/wc-messagebox/components/Alert/index.js and 1 other

**Comment by helicopters** [comment]
@DogJun hi, 稍等，我正在替换基础 API, 十分钟之后就好. ... 正好被你碰上了哈哈。

**Comment by helicopters** [comment]
@DogJun 好了, 重新安装一下即可.

**Comment by DogJun** [comment]
哈哈，我刚发现你把wc-utils中的merge函数删掉了。

**Comment by helicopters** [comment]
@DogJun  ... 现在替换成 lodash 里面的 merge 函数了. 重新安装下就好了.

**Comment by DogJun** [comment]
是的，这个问题解决了，我自己定义了一个merge函数，但是我直接把src/wc-messagebox拉到本地用有问题，弹窗内容不显示。我改为npm引用就没问题。

**Comment by helicopters** [comment]
@DogJun 你是直接把 scr/wc-messagebox 拷贝到本地吗? 如果是这样， 你还需要安装 lodash 依赖, 直接 npm 可以是因为 lodash 这个依赖自动下载了.

**Comment by DogJun** [comment]
跟lodash应该是没关系的，merge函数我自己实现了，编译的时候没有依赖报错。

**Comment by helicopters** [comment]
@DogJun  你是替换掉了 import merge from 'lodash/merge' 这句吗.

**Comment by DogJun** [comment]
换了，我在你的github项目的wc-utils中的merge函数拷贝过来本地引用了。

**Comment by DogJun** [comment]
你现在的最新的代码好似也没用lodash吧。

**Comment by DogJun** [comment]
可以了，我把merge换成lodash的就行了，谢谢哈。

**Comment by helicopters** [comment]
@DogJun 我刚自己试了下, 在编译的时候缺少两个依赖: less, less-loader, 你可能需要先安装这两个依赖。 因为代码中使用到了 less。 最新的代码中已经更新 wc-utils/merge  到 lodash/merge 了. 本地引用的依赖问题我之前没有考虑到, 现在去更改一下 文档.
