### ISSUE TITLE
使用下面rem布局，任何人的ui都会变化，包括你的，虽然不该提issues，但是还是想知道，我这么布局行不行

### ISSUE THREAD

**Issue by fooller** [helicopters/wc-messagebox#11]
(
  function (doc, win) {
    /** 获取像素比 */
    var pixelRatio = 1 / window.devicePixelRatio
    /** 通过js动态设置视口(viewport) */
    document.write('<meta name="viewport" content="width=device-width,minimum-scale=' + pixelRatio + ',maximum-scale=' + pixelRatio + '" />')
    // document.write('<meta name="viewport" content="width=device-width,initial-scale=' + pixelRatio + ',minimum-scale=' + pixelRatio + ',maximum-scale=' + pixelRatio + '" />')
    /** 条件：尺寸越大，则字体大小越大。尺寸越小，则字体大小越小。
    获取html节点 */
    var html = document.getElementsByTagName('html')[0]
    // 获取屏幕宽度
    var pageWidth = html.getBoundingClientRect().width
    // 屏幕宽度 / 固定数值 = 基准值
    html.style.fontSize = pageWidth / 16 + 'px'
  }
)(document, window)

**Comment by helicopters** [comment]
@fooller 这个呢，我如果没记错的话, 如果你只是改了 rem 根元素的值是不会有问题的。因为这里用的是px布局。你说所有的布局都变化了，除非你动态设置了 meta 头的 viewport 的值, 这样的话才会导致所有的UI变化. 如果是这样动画, 建议你fork代码然后修改一下内部的 px 值. 不过这个也是我没有考虑清楚. 应该动态做一下处理.
