### ISSUE TITLE
按钮那个地方如果用button会不会好一些，在桌面平台上

### ISSUE THREAD

**Issue by wwqgtxx** [helicopters/wc-messagebox#2]
现在的按钮用的全部都是span，但是这样的话在桌面平台上鼠标显示的就是一段文字，对用户的感知并不太良好，要是做成button用户把鼠标放上去才有能点击的感觉，这样会不会好一些

**Comment by helicopters** [comment]
@wwqgtxx hi, 我这边理解你的意思是说: 希望在桌面平台上, 鼠标移动到按钮上之后为一个手形,  也就是
cursor:pointer; 我这边已经添加更新了, 你可以重新安装查看效果. 老实说, 这段 html 是直接从 MUI 拿过来的, 我一直都是关注它在移动端的表现, pc 上没有过多的关注,haha.

**Comment by wwqgtxx** [comment]
好的，回头我更新一下试试
