### ISSUE TITLE
document is undefined

### ISSUE THREAD

**Issue by nijunjie** [helicopters/wc-messagebox#22]
按照文档在 main.js 里面引用如下
![image](https://user-images.githubusercontent.com/16549894/49003959-04646e80-f118-11e8-83c5-ada3d01df5c3.png)
然后在index.vue 中执行this.$alert('这里是内容')
报错
![image](https://user-images.githubusercontent.com/16549894/49004087-53120880-f118-11e8-8300-878f736eae27.png)
![image](https://user-images.githubusercontent.com/16549894/49004118-6de47d00-f118-11e8-8003-1f0629dcde1e.png)

请问是什么原因导致的，谢谢。

**Comment by helicopters** [comment]
你好, 看报错你是在小程序里面引用了这个组件; 但是这个组件并不支持小程序.
这个报错是因为小程序里面是没有  document 对象的.

**Comment by nijunjie** [comment]
谢谢
