### ISSUE TITLE
npm install 会出现如下警告，我想基次进行二次开发

### ISSUE THREAD

**Issue by Zeus-Iqd** [helicopters/wc-messagebox#4]
npm WARN Error: EPERM: operation not permitted, scandir 'E:\wc-messagebox\node_m               odules\editorconfig\node_modules'

**Comment by Zeus-Iqd** [comment]
请问题主要如何解决

**Comment by helicopters** [comment]
@Zeus-Iqd  hi , 貌似这个是本地安装的时候的权限问题. 有更详细的 npm-debug.log 吗.

**Comment by Zeus-Iqd** [comment]
有，方便加个qq吗

**Comment by Zeus-Iqd** [comment]
扣扣号
1042883146

**Comment by 80boys** [comment]
插件 很不错

**Comment by helicopters** [comment]
@80boys  谢谢~
