### ISSUE TITLE
options is not defined  

### ISSUE THREAD

**Issue by benmo1602** [helicopters/wc-messagebox#7]
![image](https://user-images.githubusercontent.com/22746527/34592936-8759e59c-f202-11e7-8fe9-c1f901b6a1c3.png)

**Comment by helicopters** [comment]
@caokunyu hi, 我最近修改了一下实现, 为了支持用户自定义弹窗样式. 麻烦看下你使用的版本是多少.

**Comment by benmo1602** [comment]
"wc-messagebox": "^1.9.1" 
我是 今天 早上 引入的， 在main.js 引入 是不行的 
  @helicopters

**Comment by helicopters** [comment]
@caokunyu 哈哈，方便加下微信具体了解下吗。 wx: x435074072

**Comment by benmo1602** [comment]
好的 已加

**Comment by warrior-bing** [comment]
同问，同样的错误，在main.js 里加的
